export const ADD = 'add'
export const DELETE_BY_INDEX = 'deleteByIndex'
export const ON_MOUSE_OVER = 'onMouseOver'
export const CLICK_TODOS_BY_INDEX = 'clickTodosByIndex'
export const CLICK_ALL_CHECKBOX = 'clickAllCheckbox'
export const CLEAR_TODOS = 'clearTodos'
export const ON_LONG_PRESS_BY_INDEX = 'onLongPressByIndex'
export const EDIT_TODO_BY_INDEX = 'editTodoByIndex'
